version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spotify-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - spotify-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: spotify-frontend
    ports:
      - "5173:80"
    networks:
      - spotify-net
    depends_on:
      - backend

networks:
  spotify-net:
    driver: bridge